### ISSUE TITLE
HUD Improvements

### ISSUE THREAD

**Issue by victryx** [CakeNeka/Unholy-Typing#27]
#### Description

HUD Improvements

#### Tasks

- [x] Set solid background for HUD elements
    - [x] Add new variable `backgroundUI` for every theme
- [x] Show information in a row above screen
- [x] Display Accuracy and Score in UI (they're currently being logged to the console)
