### ISSUE TITLE
UI Details

### ISSUE THREAD

**Issue by victryx** [CakeNeka/Unholy-Typing#34]
#### Description

Some light improvements to the user interface

#### Tasks

- [x] #39
- [x] Show lives left
- [x] Fix HUD upper row on smaller screens
~~- [ ] The player should visit `Settings` menu before clicking play~~
~~- Disable `Play` Button until they visit `Settings` and show a tooltip~~
- [x] #38
- [x] Fix dropdown style
