### ISSUE TITLE
Score system

### ISSUE THREAD

**Issue by victryx** [CakeNeka/Unholy-Typing#4]
#### Description

Implement scoring system

#### Tasks

- [x] Calculate typing accuracy
- [x] Mistakes subtract points
- [x] Defeated enemies add points
