### ISSUE TITLE
More UI Improvements

### ISSUE THREAD

**Issue by victryx** [CakeNeka/Unholy-Typing#41]
#### Description

Main menu UI Issues

#### Tasks

- [ ] Use 2 lines, one for each sentence in exit confirm dialogue
- [ ] `Back` button should always use a different font color
- [ ] Dropdowns in settings screen should be bigger and aligned with `settings`
- [ ] On settings screen, replace "Back" with "Let's type"
- Buttons are hard to see because their color is black over black. Do one of the following:
  - [ ] Add white border to buttons
  - [ ] Invert background and button colors.
- [ ] Whitespaces in sentences are displayed with the `·` character, this is unclear and should be clarified in a `FAQ` or `Controls` Screen
